apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: jutecrm
type: Opaque
stringData:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "jute_crm"
  DB_USER: "root"
  DB_PASS: "Passw0rd123#$"
