apiVersion: v1
kind: Service
metadata:
  name: jutecrm-backend
  namespace: jutecrm
spec:
  type: LoadBalancer
  selector:
    app: jutecrm-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
