apiVersion: apps/v1
kind: Deployment
metadata:
  name: jutecrm-backend
  namespace: jutecrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jutecrm-backend
  template:
    metadata:
      labels:
        app: jutecrm-backend
    spec:
      containers:
        - name: backend
          image: asia-south1-docker.pkg.dev/billmonitor/jutecrm/backend:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
